version: '3' 

services:

  triton:
    image: 'nvcr.io/nvidia/tritonserver:22.06-py3'
    env_file: ../.env
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command: ['tritonserver', '--model-repository=s3://nlp-medical-biller-group-datasets-mlo4/models']

  setfit_icd_service:
    build: ../pretrained_models/setfit_icd
    container_name: setfit_icd
    ports:
      - "8050:8000"
  bert_icd_service:
    build: ../pretrained_models/bert_icd
    container_name: bert_icd
    ports:
      - "8051:8000"
  main:
    build: .
    ports:
      - "8003:8000"
    environment:
      - URL_SETFIT_ICD_SERVICE=http://setfit_icd_service:8000/
      - URL_BERT_ICD_SERVICE=http://bert_icd_service:8000/
   #   - URl_DISEASE_SERVICE=http://disease-ner-service:8000/
    depends_on:
      - setfit_icd_service
      - bert_icd_service
   #   - disease-ner-service
      - triton
      


#docker run --env-file ../../.env -p8000:8000 -p8001:8001 -p8002:8002 --rm --net=host nvcr.io/nvidia/tritonserver:22.06-py3 tritonserver --model-repository=s3://nlp-medical-biller-group-datasets-mlo4/models
