version: '3' 

services:

  triton:
    image: 'nvcr.io/nvidia/tritonserver:22.06-py3'
    env_file: ../.env
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command: ['tritonserver', '--model-repository=s3://nlp-medical-biller-group-datasets-mlo4/models']

  icd-group-service:
    build: ../pretrained_models/setfit_icd
    container_name: icd
    ports:
      - "8050:8000"
  #disease-ner-service:
  #  build: ../pretrained_models/disease_ner/
  #  container_name: disease
  #  ports:
  #    - "8051:8000"
  main:
    build: .
    ports:
      - "8003:8000"
    environment:
      - URL_ICD_SERVICE=http://icd-group-service:8000/
   #   - URl_DISEASE_SERVICE=http://disease-ner-service:8000/
    depends_on:
      - icd-group-service
   #   - disease-ner-service
      - triton
      


#docker run --env-file ../../.env -p8000:8000 -p8001:8001 -p8002:8002 --rm --net=host nvcr.io/nvidia/tritonserver:22.06-py3 tritonserver --model-repository=s3://nlp-medical-biller-group-datasets-mlo4/models
