version: '3' 

services:
  icd-class-service:
    build: ../pretrained_models/icd_predict
    container_name: icd
    ports:
      - "8050:8000"
  disease-ner-service:
    build: ../pretrained_models/disease_ner/
    container_name: disease
    ports:
      - "8051:8000"
  main:
    build: .
    ports:
      - "8000:8000"
    environment:
      - URL_ICD_SERVICE=http://icd-class-service:8000/
      - URl_DISEASE_SERVICE=http://disease-ner-service:8000/
    depends_on:
      - icd-class-service
      - disease-ner-service